//! qpdf correspondence: QPDF_linearization.cc plus BitStream.cc and BitWriter.cc hint encoding responsibilities.
//! Hint stream encoder — FlateDecode-compressed binary hint tables.
//!
//! This module takes fully-populated [`PageOffsetHintTable`] and
//! [`SharedObjectHintTable`] values and serialises them into a single
//! zlib-compressed byte sequence that forms the body of the PDF hint stream
//! object (Annex F.4).
//!
//! # Layout of the uncompressed stream (Annex F.4)
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────┐
//! │  Page Offset Hint Table   (Annex F.3.1, bit-packed)     │
//! │  … byte-aligned at start                                 │
//! ├─────────────────────────────────────────────────────────┤  ← /S value
//! │  Shared Object Hint Table (Annex F.3.2, bit-packed)     │
//! │  … byte-aligned at start                                 │
//! ├─────────────────────────────────────────────────────────┤  ← /O value
//! │  Outlines Hint Table      (Annex F.3.4, 4 × 32-bit)     │  (only when
//! │  … byte-aligned at start                                 │   outlines exist)
//! └─────────────────────────────────────────────────────────┘
//! ```
//!
//! The byte offset of the Shared Object Hint Table within the **uncompressed**
//! stream is stored as the `/S` key in the hint stream's dictionary. When the
//! document has outlines, the Outlines Hint Table follows and its byte offset is
//! stored as the `/O` key (qpdf only emits it when `nobjects > 0`).
//!
//! The Thumbnail hint table (Annex F.3.3) is **not** generated by this
//! implementation.
//!
//! # Bit-packing
//!
//! Fields are packed **MSB-first** (most-significant bit first within each byte),
//! following the direction required by ISO 32000-1 Annex F.  `write_bits(value,
//! n)` takes the `n` least-significant bits of `value` and appends them to the
//! output buffer starting from the most-significant available position in the
//! current byte.
//!
//! # Fixed field widths (Annex F.3.1 / F.3.2 header tables)
//!
//! The hint-table headers use fixed widths that the spec defines per-item:
//!
//! ## Page Offset Header (Annex F.3.1, Table F.4) — 13 items, 36 bytes
//!
//! | Item | Bytes | Width | Field |
//! |------|-------|-------|-------|
//! | 1  | 0-3   | 32 | `least_object_count` |
//! | 2  | 4-7   | 32 | `location_of_first_page` |
//! | 3  | 8-9   | 16 | `bits_object_count_delta` |
//! | 4  | 10-13 | 32 | `least_page_length` |
//! | 5  | 14-15 | 16 | `bits_page_length_delta` |
//! | 6  | 16-19 | 32 | `least_content_offset` |
//! | 7  | 20-21 | 16 | `bits_content_offset_delta` |
//! | 8  | 22-25 | 32 | `least_content_length` |
//! | 9  | 26-27 | 16 | `bits_content_length_delta` |
//! | 10 | 28-29 | 16 | `bits_shared_object_count` |
//! | 11 | 30-31 | 16 | `bits_shared_object_id` |
//! | 12 | 32-33 | 16 | `bits_numerator` |
//! | 13 | 34-35 | 16 | `denominator` |
//!
//! ## Shared Object Header (Annex F.3.2, Table F.9)
//!
//! | Item | Field | Bits |
//! |------|-------|------|
//! | 1 | `first_object_number` | 32 |
//! | 2 | `location` | 32 |
//! | 3 | `first_page_entries` | 32 |
//! | 4 | `section_entries` | 32 |
//! | 5 | `bits_group_object_count` | 16 |
//! | 6 | `least_length` | 32 |
//! | 7 | `bits_length_delta` | 16 |
//!
//! ## Encoding decision
//!
//! Default builds use flate2's miniz_oxide backend at `Compression::default()`
//! (level 6, matching qpdf's `Z_DEFAULT_COMPRESSION`). The two encoders produce
//! same-size output with different internal bytes. With the `qpdf-zlib-compat`
//! feature flate2 links against classic libz1g and the hint stream becomes
//! byte-identical to qpdf's; the gated test in `tests/zlib_compat_tests.rs`
//! pins that invariant. Structural validity is independently checked via
//! `qpdf --check-linearization` on the round-tripped fixtures.

use super::hint_page::PageOffsetHintTable;
use super::hint_shared::SharedObjectHintTable;
use crate::bit_writer::BitWriter;
use crate::pipeline::buffer::Buffer;
use crate::pipeline::count::Count;
use crate::pipeline::flate::{Flate, FlateAction, DEFAULT_OUT_BUFFER_SIZE};
use crate::pipeline::{Pipeline, PipelineResult};

// ---------------------------------------------------------------------------
// HintStreamBytes — result type
// ---------------------------------------------------------------------------

/// Output of [`encode_hint_stream`].
///
/// Contains both the uncompressed and FlateDecode-compressed forms of the
/// hint stream, plus the byte offset of the Shared Object section within the
/// uncompressed stream (the PDF `/S` key value).
pub struct HintStreamBytes {
    /// The raw, uncompressed bit-packed hint stream.
    pub uncompressed: Vec<u8>,
    /// The FlateDecode-compressed hint stream (zlib/deflate wrapped).
    pub compressed: Vec<u8>,
    /// Byte offset of the Shared Object Hint Table section within
    /// `uncompressed`.  This is the value to write as `/S` in the hint
    /// stream object's dictionary.
    pub shared_section_offset_in_uncompressed: usize,
    /// Byte offset of the Outlines Hint Table section within `uncompressed`,
    /// when one was emitted (the value to write as `/O` in the hint stream
    /// object's dictionary). `None` when the document has no outlines, in which
    /// case the `/O` key is omitted (matching qpdf's `if (O)` guard).
    pub outline_section_offset_in_uncompressed: Option<usize>,
}

/// Outlines (generic) hint table — qpdf's `HGeneric` (Annex F.3.4).
///
/// Emitted after the Shared Object Hint Table when the document has outlines.
/// All four fields are fixed 32-bit, written MSB-first (qpdf's `writeHGeneric`,
/// QPDF_linearization.cc:1749-1755).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct OutlineHintTable {
    /// Renumbered object number of the first outline output unit (the object —
    /// or ObjStm container — holding the `/Outlines` dictionary).
    pub first_object: u32,
    /// "Virtual" byte offset of that first unit, WITHOUT the hint stream object
    /// bytes (qpdf's `adjusted_offset` adds `/H[1]` back for offsets at or after
    /// the hint stream — same convention as the Shared Object table `location`).
    pub first_object_offset: u32,
    /// Number of outline output units (containers / plain objects).
    pub nobjects: u32,
    /// Total byte length of the `nobjects` consecutive output units.
    pub group_length: u32,
}

// ---------------------------------------------------------------------------
// Page Offset Hint Table encoder (Annex F.3.1)
// ---------------------------------------------------------------------------

/// Verify that `value` fits in `slot_bits` and write it; otherwise return an
/// `Unsupported` error.  `field_name` is included in the error so the caller
/// can identify which Annex F field overflowed.
fn write_bits_checked(
    writer: &mut BitWriter<'_>,
    value: u64,
    slot_bits: usize,
    field_name: &str,
) -> crate::Result<()> {
    let max = if slot_bits >= 64 {
        u64::MAX
    } else {
        (1u64 << slot_bits) - 1
    };
    if value > max {
        return Err(crate::Error::Unsupported(format!(
            "hint stream: {field_name} value {value} does not fit in {slot_bits}-bit Annex F slot \
             (max {max}) — file likely exceeds 4 GiB or has a malformed plan"
        )));
    }
    writer.write_bits(value, slot_bits)?;
    Ok(())
}

fn encode_page_offset_header(
    writer: &mut BitWriter<'_>,
    t: &PageOffsetHintTable,
) -> crate::Result<()> {
    let h = &t.header;
    // Items numbered as in Annex F.3.1, Table F.4.
    // 5 × 32-bit fields + 8 × 16-bit fields = 5×4 + 8×2 = 36 bytes total.
    //
    // Item 1: least_object_count (32-bit)
    write_bits_checked(
        writer,
        h.least_object_count as u64,
        32,
        "least_object_count",
    )?;
    // Item 2: location_of_first_page (32-bit)
    write_bits_checked(
        writer,
        h.location_of_first_page,
        32,
        "location_of_first_page",
    )?;
    // Item 3: bits_object_count_delta (16-bit)
    write_bits_checked(
        writer,
        h.bits_object_count_delta as u64,
        16,
        "bits_object_count_delta",
    )?;
    // Item 4: least_page_length (32-bit)
    write_bits_checked(writer, h.least_page_length, 32, "least_page_length")?;
    // Item 5: bits_page_length_delta (16-bit)
    write_bits_checked(
        writer,
        h.bits_page_length_delta as u64,
        16,
        "bits_page_length_delta",
    )?;
    // Item 6: least_content_offset (32-bit)
    write_bits_checked(writer, h.least_content_offset, 32, "least_content_offset")?;
    // Item 7: bits_content_offset_delta (16-bit)
    write_bits_checked(
        writer,
        h.bits_content_offset_delta as u64,
        16,
        "bits_content_offset_delta",
    )?;
    // Item 8: least_content_length (32-bit)
    write_bits_checked(writer, h.least_content_length, 32, "least_content_length")?;
    // Item 9: bits_content_length_delta (16-bit)
    write_bits_checked(
        writer,
        h.bits_content_length_delta as u64,
        16,
        "bits_content_length_delta",
    )?;
    // Item 10: bits_shared_object_count (16-bit)
    write_bits_checked(
        writer,
        h.bits_shared_object_count as u64,
        16,
        "bits_shared_object_count",
    )?;
    // Item 11: bits_shared_object_id (16-bit)
    write_bits_checked(
        writer,
        h.bits_shared_object_id as u64,
        16,
        "bits_shared_object_id",
    )?;
    // Item 12: bits_numerator (16-bit)
    write_bits_checked(writer, h.bits_numerator as u64, 16, "bits_numerator")?;
    // Item 13: denominator (16-bit)
    write_bits_checked(writer, h.denominator as u64, 16, "denominator")?;
    // Header total: 5×32 + 8×16 = 160 + 128 = 288 bits = 36 bytes (always aligned).
    Ok(())
}

fn encode_page_offset_entries(
    writer: &mut BitWriter<'_>,
    t: &PageOffsetHintTable,
) -> PipelineResult<()> {
    let h = &t.header;

    // qpdf reads the page-offset section in **column order** via
    // `load_vector_int` / `load_vector_vector` with `skipToNextByte()` after
    // each column.  The previous implementation wrote rows (each entry's
    // fields followed by the next entry's fields) which qpdf cannot parse.
    //
    // Per `Lin::readHPageOffset` (qpdf libqpdf/QPDF_linearization.cc):
    //   col 1: delta_nobjects        (bits_object_count_delta bits × N pages)
    //   col 2: delta_page_length     (bits_page_length_delta bits × N pages)
    //   col 3: nshared_objects       (bits_shared_object_count bits × N pages)
    //   col 4: shared_identifiers    (variable — bits_shared_object_id bits × Σ nshared per page)
    //   col 5: shared_numerators     (variable — bits_numerator bits × Σ nshared per page)
    //   col 6: delta_content_offset  (bits_content_offset_delta bits × N pages)
    //   col 7: delta_content_length  (bits_content_length_delta bits × N pages)
    //   …with a byte alignment after each column.

    // col 1
    for entry in &t.entries {
        writer.write_bits(
            entry.object_count_minus_least as u64,
            h.bits_object_count_delta as usize,
        )?;
    }
    writer.flush()?;

    // col 2
    for entry in &t.entries {
        writer.write_bits(
            entry.page_length_minus_least,
            h.bits_page_length_delta as usize,
        )?;
    }
    writer.flush()?;

    // col 3
    for entry in &t.entries {
        writer.write_bits(
            entry.shared_object_count as u64,
            h.bits_shared_object_count as usize,
        )?;
    }
    writer.flush()?;

    // col 4: per-page shared identifiers (variable-length per page)
    for entry in &t.entries {
        for &id in &entry.shared_object_ids {
            writer.write_bits(id as u64, h.bits_shared_object_id as usize)?;
        }
    }
    writer.flush()?;

    // col 5: per-page shared numerators
    for entry in &t.entries {
        for &num in &entry.shared_object_numerators {
            writer.write_bits(num as u64, h.bits_numerator as usize)?;
        }
    }
    writer.flush()?;

    // col 6
    for entry in &t.entries {
        writer.write_bits(
            entry.content_stream_offset,
            h.bits_content_offset_delta as usize,
        )?;
    }
    writer.flush()?;

    // col 7
    for entry in &t.entries {
        writer.write_bits(
            entry.content_stream_length,
            h.bits_content_length_delta as usize,
        )?;
    }
    writer.flush()?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Shared Object Hint Table encoder (Annex F.3.2)
// ---------------------------------------------------------------------------

fn encode_shared_object_header(
    writer: &mut BitWriter<'_>,
    t: &SharedObjectHintTable,
) -> crate::Result<()> {
    let h = &t.header;
    // Items numbered as in Annex F.3.2, Table F.9.
    write_bits_checked(
        writer,
        h.first_object_number as u64,
        32,
        "shared.first_object_number",
    )?;
    write_bits_checked(writer, h.location, 32, "shared.location")?;
    write_bits_checked(
        writer,
        h.first_page_entries as u64,
        32,
        "shared.first_page_entries",
    )?;
    write_bits_checked(
        writer,
        h.section_entries as u64,
        32,
        "shared.section_entries",
    )?;
    write_bits_checked(
        writer,
        h.bits_group_object_count as u64,
        16,
        "shared.bits_group_object_count",
    )?;
    write_bits_checked(writer, h.least_length, 32, "shared.least_length")?;
    write_bits_checked(
        writer,
        h.bits_length_delta as u64,
        16,
        "shared.bits_length_delta",
    )?;
    // Header total: 5×32 + 2×16 = 160 + 32 = 192 bits = 24 bytes (always aligned).
    Ok(())
}

fn encode_shared_object_entries(
    writer: &mut BitWriter<'_>,
    t: &SharedObjectHintTable,
) -> PipelineResult<()> {
    let h = &t.header;

    // qpdf reads shared-object entries column-wise (per `Lin::readHSharedObject`):
    //   col 1: delta_group_length    (bits_length_delta bits × N entries)
    //   col 2: signature_present     (1 bit × N entries)
    //   col 3: nobjects_minus_one    (bits_group_object_count bits × N entries)
    //   …with a byte alignment after each column.
    //
    // (Signatures, when present, are inline with the signature_present
    // column per qpdf; we never emit signatures, so this is a no-op.)
    //
    // col 1: delta_group_length
    for entry in &t.objects {
        writer.write_bits(
            entry.length_minus_least as u64,
            h.bits_length_delta as usize,
        )?;
    }
    writer.flush()?;

    // col 2: signature_present (1 bit per entry, plus 128-bit signature if set)
    for entry in &t.objects {
        writer.write_bits(if entry.signature_present { 1 } else { 0 }, 1)?;
        if entry.signature_present {
            if let Some(sig) = &entry.signature {
                for &byte in sig {
                    writer.write_bits(byte as u64, 8)?;
                }
            }
        }
    }
    writer.flush()?;

    // col 3: nobjects_minus_one
    for entry in &t.objects {
        writer.write_bits(
            entry.nobjects_minus_one as u64,
            h.bits_group_object_count as usize,
        )?;
    }
    writer.flush()?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

fn encode_page_section(
    writer: &mut BitWriter<'_>,
    page_offset: &PageOffsetHintTable,
) -> crate::Result<()> {
    encode_page_offset_header(writer, page_offset)?;
    writer.flush()?;
    encode_page_offset_entries(writer, page_offset)?;
    writer.flush()?;
    Ok(())
}

fn encode_shared_section(
    writer: &mut BitWriter<'_>,
    shared_object: &SharedObjectHintTable,
) -> crate::Result<()> {
    encode_shared_object_header(writer, shared_object)?;
    writer.flush()?;
    encode_shared_object_entries(writer, shared_object)?;
    writer.flush()?;
    Ok(())
}

fn encode_outline_section(
    writer: &mut BitWriter<'_>,
    outline: &OutlineHintTable,
) -> PipelineResult<()> {
    writer.write_bits(outline.first_object as u64, 32)?;
    writer.write_bits(outline.first_object_offset as u64, 32)?;
    writer.write_bits(outline.nobjects as u64, 32)?;
    writer.write_bits(outline.group_length as u64, 32)?;
    writer.flush()
}

fn checked_hint_offset<T>(count: u64, key: &str) -> crate::Result<T>
where
    T: TryFrom<u64>,
{
    T::try_from(count).map_err(|_| {
        crate::Error::Unsupported(format!(
            "hint {key} offset does not fit {}",
            std::any::type_name::<T>()
        ))
    })
}

#[cfg(test)]
fn encode_hint_sections_for_test(
    tables: &(PageOffsetHintTable, SharedObjectHintTable),
    mut terminal: impl Pipeline,
) -> crate::Result<()> {
    let mut count = Count::new("count hint stream", &mut terminal);
    {
        let mut writer = BitWriter::new(&mut count);
        encode_page_section(&mut writer, &tables.0)?;
        writer.flush()?;
    }
    {
        let mut writer = BitWriter::new(&mut count);
        encode_shared_section(&mut writer, &tables.1)?;
        writer.flush()?;
    }
    count.finish()?;
    Ok(())
}

/// Encode a Page Offset Hint Table and a Shared Object Hint Table into a
/// single hint stream, compressed with FlateDecode (zlib deflate).
///
/// Returns [`HintStreamBytes`] which contains:
/// - the raw uncompressed bit-packed stream (`uncompressed`)
/// - the FlateDecode-compressed form (`compressed`)
/// - the byte offset of the Shared Object section within `uncompressed`
///   (the `/S` value for the hint stream dictionary)
///
/// # Encoding details
///
/// - Bit order: MSB-first (most-significant bit first within each byte)
/// - Section alignment: each hint-table section begins on a byte boundary
/// - Per-entry alignment: each per-page and per-object entry begins on a byte boundary
/// - Compression: the qpdf-shaped Flate pipeline at the default level (6)
///
/// # Placeholder fields
///
/// Fields that have not yet been back-patched are encoded as
/// `0`.  For fields whose bit-width is `0` (e.g. `bits_page_length_delta = 0`
/// while lengths are still placeholder), `write_bits(value, 0)` is a no-op;
/// those bits are simply absent until the stream is regenerated after
/// back-patching.
///
/// # Errors
///
/// Returns [`crate::Error::Unsupported`] when a Page Offset or Shared Object
/// header field value does not fit in its fixed-width Annex F slot (e.g. a value
/// exceeding `u32::MAX` for a 32-bit slot), which typically indicates a file
/// larger than 4 GiB or a malformed linearization plan.
pub fn encode_hint_stream(
    page_offset: &PageOffsetHintTable,
    shared_object: &SharedObjectHintTable,
    outline: Option<&OutlineHintTable>,
) -> crate::Result<HintStreamBytes> {
    encode_hint_stream_with_out_buffer_size(
        page_offset,
        shared_object,
        outline,
        DEFAULT_OUT_BUFFER_SIZE,
    )
}

fn encode_hint_stream_with_out_buffer_size(
    page_offset: &PageOffsetHintTable,
    shared_object: &SharedObjectHintTable,
    outline: Option<&OutlineHintTable>,
    out_buffer_size: usize,
) -> crate::Result<HintStreamBytes> {
    let mut compressed_sink = Buffer::new("compressed hint stream", None);
    let uncompressed;
    let shared_section_offset;
    let outline_section_offset;
    {
        let mut flate = Flate::new(
            "compress hint stream",
            &mut compressed_sink,
            FlateAction::Deflate,
            out_buffer_size,
        )?;
        let mut raw = Buffer::new("raw hint stream", Some(&mut flate));
        {
            let mut count = Count::new("count hint stream", &mut raw);
            {
                let mut writer = BitWriter::new(&mut count);
                encode_page_section(&mut writer, page_offset)?;
                writer.flush()?;
            }
            shared_section_offset = checked_hint_offset(count.count(), "/S")?;
            {
                let mut writer = BitWriter::new(&mut count);
                encode_shared_section(&mut writer, shared_object)?;
                writer.flush()?;
            }
            outline_section_offset = if let Some(outline) = outline {
                let offset = checked_hint_offset(count.count(), "/O")?;
                let mut writer = BitWriter::new(&mut count);
                encode_outline_section(&mut writer, outline)?;
                writer.flush()?;
                Some(offset)
            } else {
                None
            };
            count.finish()?;
        }
        uncompressed = raw.take_buffer()?;
    }
    let compressed = compressed_sink.take_buffer()?;

    Ok(HintStreamBytes {
        uncompressed,
        compressed,
        shared_section_offset_in_uncompressed: shared_section_offset,
        outline_section_offset_in_uncompressed: outline_section_offset,
    })
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::linearization::hint_page::PageOffsetHintTable;
    use crate::linearization::hint_shared::{SharedObjectEntry, SharedObjectHintTable};
    use crate::linearization::plan::{LinearizationPlan, PageHintEntry, SharedObjectHintEntry};
    use crate::linearization::renumber::RenumberMap;
    use crate::pipeline::{Pipeline, PipelineError, PipelineResult};
    use crate::ObjectRef;

    struct FailingSink {
        identifier: &'static str,
        fail_at_write: Option<usize>,
        writes: usize,
        fail_finish: bool,
    }

    impl FailingSink {
        fn new(identifier: &'static str) -> Self {
            Self {
                identifier,
                fail_at_write: Some(0),
                writes: 0,
                fail_finish: false,
            }
        }

        fn at_write(identifier: &'static str, fail_at_write: usize) -> Self {
            Self {
                identifier,
                fail_at_write: Some(fail_at_write),
                writes: 0,
                fail_finish: false,
            }
        }

        fn at_finish(identifier: &'static str) -> Self {
            Self {
                identifier,
                fail_at_write: None,
                writes: 0,
                fail_finish: true,
            }
        }
    }

    impl Pipeline for FailingSink {
        fn identifier(&self) -> &str {
            self.identifier
        }

        fn write(&mut self, _data: &[u8]) -> PipelineResult<()> {
            if self.fail_at_write == Some(self.writes) {
                return Err(PipelineError::logic(format!(
                    "{}: write failed",
                    self.identifier()
                )));
            }
            self.writes += 1;
            Ok(())
        }

        fn finish(&mut self) -> PipelineResult<()> {
            if self.fail_finish {
                Err(PipelineError::logic(format!(
                    "{}: finish failed",
                    self.identifier()
                )))
            } else {
                Ok(())
            }
        }
    }

    // -----------------------------------------------------------------------
    // Fixture helpers
    // -----------------------------------------------------------------------

    /// Single-page plan with no shared objects.
    fn single_page_plan() -> LinearizationPlan {
        LinearizationPlan {
            part2_objects: vec![
                ObjectRef::new(3, 0),
                ObjectRef::new(2, 0),
                ObjectRef::new(1, 0),
            ],
            total_object_count: 3,
            page_hints: vec![PageHintEntry {
                page_ref: ObjectRef::new(3, 0),
                first_object_index: 0,
                object_count: 3,
                byte_length: 0,
            }],
            ..Default::default()
        }
    }

    fn minimal_tables() -> (PageOffsetHintTable, SharedObjectHintTable) {
        let plan = single_page_plan();
        let renumber = RenumberMap::from_plan(&plan);
        let page_offset = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let shared_object = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        (page_offset, shared_object)
    }

    fn nonzero_tables() -> (PageOffsetHintTable, SharedObjectHintTable) {
        let (mut page_offset, mut shared_object) = minimal_tables();
        page_offset.header.bits_object_count_delta = 8;
        page_offset.header.bits_page_length_delta = 8;
        page_offset.header.bits_shared_object_count = 8;
        page_offset.header.bits_shared_object_id = 8;
        page_offset.header.bits_numerator = 8;
        page_offset.header.bits_content_offset_delta = 8;
        page_offset.header.bits_content_length_delta = 8;
        let page = &mut page_offset.entries[0];
        page.object_count_minus_least = 1;
        page.page_length_minus_least = 1;
        page.shared_object_count = 1;
        page.shared_object_ids = vec![1];
        page.shared_object_numerators = vec![1];
        page.content_stream_offset = 1;
        page.content_stream_length = 1;

        shared_object.header.first_page_entries = 1;
        shared_object.header.section_entries = 1;
        shared_object.header.bits_group_object_count = 8;
        shared_object.header.bits_length_delta = 8;
        shared_object.objects = vec![SharedObjectEntry {
            length_minus_least: 1,
            signature_present: true,
            signature: Some([0xA5; 16]),
            nobjects_minus_one: 1,
        }];
        (page_offset, shared_object)
    }

    #[test]
    fn shared_section_emits_qpdf_columns_without_group_preamble() {
        let (page_offset, mut shared_object) = minimal_tables();
        shared_object.header.first_page_entries = 1;
        shared_object.header.section_entries = 1;
        shared_object.header.bits_group_object_count = 8;
        shared_object.header.bits_length_delta = 8;
        shared_object.objects = vec![SharedObjectEntry {
            length_minus_least: 0x2a,
            signature_present: false,
            signature: None,
            nobjects_minus_one: 0x3c,
        }];

        let encoded = encode_hint_stream(&page_offset, &shared_object, None).expect("encode");
        let decoded = crate::linearization::show::read_h_shared_object(
            &encoded.uncompressed[encoded.shared_section_offset_in_uncompressed..],
        )
        .expect("decode qpdf-shaped shared section");
        let entry = &decoded.entries[0];

        assert_eq!(entry.delta_group_length, 0x2a);
        assert!(!entry.signature_present);
        assert_eq!(entry.nobjects_minus_one, 0x3c);
    }

    #[test]
    fn hint_encoding_maps_pipeline_logic_error_to_qpdf_internal_category() {
        let err = encode_hint_sections_for_test(&minimal_tables(), FailingSink::new("hint sink"))
            .unwrap_err();
        assert!(matches!(
            err,
            crate::Error::Internal(ref message) if message == "hint sink: write failed"
        ));
    }

    #[test]
    fn checked_hint_offset_maps_conversion_failure_to_the_target_type() {
        let err = checked_hint_offset::<u8>(u64::from(u8::MAX) + 1, "/S").unwrap_err();
        assert!(matches!(
            err,
            crate::Error::Unsupported(ref message)
                if message == "hint /S offset does not fit u8"
        ));
    }

    #[test]
    fn hint_encoding_maps_flate_runtime_error_to_qpdf_system_category() {
        let tables = minimal_tables();
        let err = encode_hint_stream_with_out_buffer_size(&tables.0, &tables.1, None, 0)
            .err()
            .expect("zero output buffer must fail");
        assert!(matches!(
            err,
            crate::Error::System(ref message)
                if message == "Pl_Flate: output buffer size must be greater than zero"
        ));
    }

    #[test]
    fn hint_encoding_propagates_page_and_shared_section_write_and_finish_errors() {
        let tables = nonzero_tables();
        let encoded = encode_hint_stream(&tables.0, &tables.1, None).unwrap();

        for fail_at_write in 0..encoded.uncompressed.len() {
            let err = encode_hint_sections_for_test(
                &tables,
                FailingSink::at_write("hint sink", fail_at_write),
            )
            .unwrap_err();
            assert!(matches!(
                err,
                crate::Error::Internal(ref message) if message == "hint sink: write failed"
            ));
        }

        encode_hint_sections_for_test(
            &tables,
            FailingSink::at_write("hint sink", encoded.uncompressed.len()),
        )
        .unwrap();

        let err = encode_hint_sections_for_test(&tables, FailingSink::at_finish("hint sink"))
            .unwrap_err();
        assert!(matches!(
            err,
            crate::Error::Internal(ref message) if message == "hint sink: finish failed"
        ));
    }

    /// Two-page plan with two shared objects referenced by both pages.
    fn two_page_plan_with_shared() -> LinearizationPlan {
        LinearizationPlan {
            part2_objects: vec![ObjectRef::new(3, 0), ObjectRef::new(6, 0)],
            part3_objects: vec![ObjectRef::new(5, 0), ObjectRef::new(8, 0)],
            part4_other_pages_private: vec![ObjectRef::new(4, 0), ObjectRef::new(7, 0)],
            total_object_count: 8,
            page_hints: vec![
                PageHintEntry {
                    page_ref: ObjectRef::new(3, 0),
                    first_object_index: 0,
                    object_count: 3,
                    byte_length: 0,
                },
                PageHintEntry {
                    page_ref: ObjectRef::new(4, 0),
                    first_object_index: 0,
                    object_count: 5,
                    byte_length: 0,
                },
            ],
            shared_hints: vec![
                SharedObjectHintEntry {
                    object_ref: ObjectRef::new(5, 0),
                    referencing_pages: vec![0, 1],
                },
                SharedObjectHintEntry {
                    object_ref: ObjectRef::new(8, 0),
                    referencing_pages: vec![0, 1],
                },
            ],
            ..Default::default()
        }
    }

    // -----------------------------------------------------------------------
    // encode_hint_stream: single-page fixture
    // -----------------------------------------------------------------------

    #[test]
    fn single_page_encode_does_not_panic() {
        let plan = single_page_plan();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let _ = encode_hint_stream(&po, &so, None).expect("encode"); // must not panic
    }

    #[test]
    fn single_page_shared_section_offset_is_positive() {
        let plan = single_page_plan();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");
        assert!(
            result.shared_section_offset_in_uncompressed > 0,
            "shared section must start after the page offset section"
        );
    }

    #[test]
    fn single_page_compressed_starts_with_zlib_header() {
        let plan = single_page_plan();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");
        assert!(
            result.compressed.len() >= 2,
            "compressed output must have at least 2 bytes (zlib header)"
        );
        // zlib CMF byte: 0x78 (deflate, window size 32 KB).
        // FLG byte encodes level: 0x9C (level 1-6), 0xDA (level 7-9), 0x01 (fastest).
        assert_eq!(
            result.compressed[0], 0x78,
            "first byte must be 0x78 (zlib CMF)"
        );
        assert!(
            result.compressed[1] == 0x9C
                || result.compressed[1] == 0xDA
                || result.compressed[1] == 0x01,
            "second byte must be a valid zlib FLG (0x9C, 0xDA, or 0x01), got 0x{:02X}",
            result.compressed[1]
        );
    }

    #[test]
    fn single_page_shared_section_within_uncompressed() {
        let plan = single_page_plan();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");
        assert!(
            result.shared_section_offset_in_uncompressed <= result.uncompressed.len(),
            "shared section offset must be within the uncompressed stream"
        );
    }

    // -----------------------------------------------------------------------
    // encode_hint_stream: two-page with shared objects
    // -----------------------------------------------------------------------

    #[test]
    fn two_page_encode_does_not_panic() {
        let plan = two_page_plan_with_shared();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let _ = encode_hint_stream(&po, &so, None).expect("encode");
    }

    #[test]
    fn two_page_shared_section_offset_is_positive() {
        let plan = two_page_plan_with_shared();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");
        assert!(result.shared_section_offset_in_uncompressed > 0);
    }

    #[test]
    fn two_page_compressed_starts_with_zlib_header() {
        let plan = two_page_plan_with_shared();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");
        assert!(result.compressed.len() >= 2);
        assert_eq!(result.compressed[0], 0x78);
    }

    #[test]
    fn two_page_uncompressed_larger_than_single_page() {
        let single_plan = single_page_plan();
        let renumber_s = RenumberMap::from_plan(&single_plan);
        let po_s = PageOffsetHintTable::from_plan(
            &single_plan,
            &renumber_s,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so_s = SharedObjectHintTable::from_plan(
            &single_plan,
            &renumber_s,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let single_result = encode_hint_stream(&po_s, &so_s, None).expect("encode");

        let two_plan = two_page_plan_with_shared();
        let renumber_t = RenumberMap::from_plan(&two_plan);
        let po_t = PageOffsetHintTable::from_plan(
            &two_plan,
            &renumber_t,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so_t = SharedObjectHintTable::from_plan(
            &two_plan,
            &renumber_t,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let two_result = encode_hint_stream(&po_t, &so_t, None).expect("encode");

        assert!(
            two_result.uncompressed.len() > single_result.uncompressed.len(),
            "two-page plan with shared objects must produce a larger stream"
        );
    }

    // -----------------------------------------------------------------------
    // encode_hint_stream: degenerate (no shared objects)
    // -----------------------------------------------------------------------

    #[test]
    fn no_shared_encode_succeeds() {
        let plan = single_page_plan(); // has no shared objects
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");
        // Even with no shared objects the shared section header is emitted,
        // so shared_section_offset_in_uncompressed must be > 0.
        assert!(result.shared_section_offset_in_uncompressed > 0);
        assert!(!result.uncompressed.is_empty());
        assert!(!result.compressed.is_empty());
    }

    // -----------------------------------------------------------------------
    // Page Offset Header fixed size check (32 bytes with placeholder data)
    // -----------------------------------------------------------------------

    #[test]
    fn page_offset_header_size_is_36_bytes() {
        // The header has:
        //   5 × 32-bit fields = 160 bits
        //   8 × 16-bit fields = 128 bits
        //   Total = 288 bits = 36 bytes
        //
        // A single-page plan with all bit-widths = 0 (placeholders):
        //   - Header: 36 bytes
        //   - Entries: 1 entry, byte-aligned start (noop since header already aligned),
        //     then 0-bit fields → 0 bytes emitted in entries
        //   - align_to_byte after entries: noop
        //   → shared section starts at byte 36
        let plan = single_page_plan();
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");

        assert_eq!(
            result.shared_section_offset_in_uncompressed, 36,
            "single-page plan with all-zero bit widths: shared section must start at byte 36"
        );
    }

    // -----------------------------------------------------------------------
    // Shared Object Header fixed size check (24 bytes)
    // -----------------------------------------------------------------------

    #[test]
    fn shared_object_header_total_size() {
        // The shared object header has:
        //   5 × 32-bit fields = 160 bits
        //   2 × 16-bit fields = 32 bits
        //   Total = 192 bits = 24 bytes
        //
        // With no shared objects (degenerate), no object entries are emitted.
        // So the total uncompressed length is:
        //   36 (page offset header) + 24 (shared object header) = 60 bytes.
        let plan = single_page_plan(); // no shared objects
        let renumber = RenumberMap::from_plan(&plan);
        let po = PageOffsetHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let so = SharedObjectHintTable::from_plan(
            &plan,
            &renumber,
            &Default::default(),
            &Default::default(),
            &Default::default(),
        );
        let result = encode_hint_stream(&po, &so, None).expect("encode");

        assert_eq!(
            result.uncompressed.len(),
            60,
            "single-page no-shared plan: uncompressed stream must be 60 bytes (36 + 24)"
        );
    }
}
