#!/usr/bin/env bash
set -euo pipefail

# Regenerate all golden reference outputs under tests/golden/references/.
# Also regenerates derived fixtures under tests/fixtures/compat/ if they don't exist.
#
# Requirements: qpdf 11.9.0 (exact version) installed on PATH — golden bytes
# are tied to a specific upstream zlib/encoder flavour so a different qpdf
# would silently drift the references.
# Usage: bash tests/golden/regenerate.sh

ROOT="$(git rev-parse --show-toplevel)"
FIX="$ROOT/tests/fixtures/compat"
REF="$ROOT/tests/golden/references"

REQUIRED_QPDF_VERSION="11.9.0"

echo "=== qpdf version ==="
ACTUAL_QPDF_VERSION="$(qpdf --version | head -1 | awk '{print $3}')"
echo "qpdf version $ACTUAL_QPDF_VERSION (required: $REQUIRED_QPDF_VERSION)"
if [[ "$ACTUAL_QPDF_VERSION" != "$REQUIRED_QPDF_VERSION" ]]; then
    echo "ERROR: qpdf $REQUIRED_QPDF_VERSION is required for byte-stable golden" >&2
    echo "       outputs; got $ACTUAL_QPDF_VERSION. Install the required version" >&2
    echo "       or bump tests/golden/README.md and re-bless the matrix." >&2
    exit 1
fi
echo ""

# ---------------------------------------------------------------------------
# Phase 1: Derive new fixtures from existing base fixtures (skip if present)
# ---------------------------------------------------------------------------

if [[ ! -f "$FIX/linearized-one-page.pdf" ]]; then
    echo "Generating linearized-one-page.pdf ..."
    qpdf --linearize --warning-exit-0 "$FIX/one-page.pdf" "$FIX/linearized-one-page.pdf"
else
    echo "Skipping linearized-one-page.pdf (already exists)"
fi

if [[ ! -f "$FIX/encrypted-r4-three-page.pdf" ]]; then
    echo "Generating encrypted-r4-three-page.pdf ..."
    qpdf --encrypt "" "" 128 --use-aes=y -- --warning-exit-0 \
        "$FIX/three-page.pdf" "$FIX/encrypted-r4-three-page.pdf"
else
    echo "Skipping encrypted-r4-three-page.pdf (already exists)"
fi

# ObjStm-bearing input (flpdf-zbf9): a cross-reference-stream + object-stream
# input, used to verify the linearized writer drops the source's structural
# containers (/Type /ObjStm, /Type /XRef) instead of leaking them.
if [[ ! -f "$FIX/three-page-objstm.pdf" ]]; then
    echo "Generating three-page-objstm.pdf ..."
    qpdf --object-streams=generate --warning-exit-0 \
        "$FIX/three-page.pdf" "$FIX/three-page-objstm.pdf"
else
    echo "Skipping three-page-objstm.pdf (already exists)"
fi

if [[ ! -f "$FIX/attachment-two-page.pdf" ]]; then
    echo "Generating attachment-two-page.pdf ..."
    # 1) Create a private temp directory (avoids the world-writable /tmp
    #    symlink-attack surface) and use a stable basename inside it.
    # 2) qpdf's --key / --filename force the embedded attachment metadata
    #    names regardless of the source path's directory.
    # 3) --static-id on the main qpdf invocation pins the trailer /ID so
    #    the output is byte-stable across runs (without it qpdf seeds the
    #    /ID from time and file metadata).
    TMPDIR_ATT="$(mktemp -d)"
    TMPFILE="$TMPDIR_ATT/attachment.txt"
    trap 'rm -rf "$TMPDIR_ATT"' EXIT
    printf "This is a small text attachment for PDF fixture testing.\nGenerated by flpdf test corpus setup.\n" \
        > "$TMPFILE"
    qpdf --add-attachment "$TMPFILE" \
        --key=attachment.txt \
        --filename=attachment.txt \
        --creationdate=D:20260101000000Z \
        --moddate=D:20260101000000Z \
        -- --warning-exit-0 --static-id \
        "$FIX/two-page.pdf" "$FIX/attachment-two-page.pdf"
    trap - EXIT
    rm -rf "$TMPDIR_ATT"
else
    echo "Skipping attachment-two-page.pdf (already exists)"
fi

if [[ ! -f "$FIX/lone-flate-l9.pdf" ]]; then
    echo "Generating lone-flate-l9.pdf ..."
    # A single-page PDF whose content stream is large enough that zlib level 9
    # and level 6 produce DIFFERENT compressed bytes (a tiny stream would not,
    # giving a false-green parity test). The content is fully deterministic
    # (no RNG). qpdf re-encodes it to a lone /FlateDecode at level 9; flpdf must
    # PRESERVE those bytes verbatim (qpdf's default), so re-encoding at level 6
    # would diverge. --object-streams=disable keeps the content stream as an
    # individual body object (classic xref, no ObjStm) so the parity is direct.
    TMPDIR_L9="$(mktemp -d)"
    trap 'rm -rf "$TMPDIR_L9"' EXIT
    python3 - "$TMPDIR_L9/raw.pdf" <<'PY'
import sys
ops = b""
for i in range(600):
    ops += b"%d %d %d %d re f\n" % (i % 500, (i * 7) % 700, (i * 3) % 40 + 5, (i * 5) % 40 + 5)
def obj(n, body): return b"%d 0 obj\n" % n + body + b"\nendobj\n"
o1 = obj(1, b"<< /Type /Catalog /Pages 2 0 R >>")
o2 = obj(2, b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
o3 = obj(3, b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << >> /Contents 4 0 R >>")
o4 = obj(4, b"<< /Length %d >>\nstream\n" % len(ops) + ops + b"\nendstream")
body = b"%PDF-1.4\n"
offsets = []
for o in (o1, o2, o3, o4):
    offsets.append(len(body)); body += o
xref_pos = len(body)
body += b"xref\n0 5\n0000000000 65535 f \n"
for off in offsets:
    body += b"%010d 00000 n \n" % off
body += b"trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % xref_pos
open(sys.argv[1], "wb").write(body)
PY
    qpdf --recompress-flate --compression-level=9 --object-streams=disable \
        --stream-data=compress --static-id --warning-exit-0 \
        "$TMPDIR_L9/raw.pdf" "$FIX/lone-flate-l9.pdf"
    trap - EXIT
    rm -rf "$TMPDIR_L9"
else
    echo "Skipping lone-flate-l9.pdf (already exists)"
fi

if [[ ! -f "$FIX/shared-stream-objstm.pdf" ]]; then
    echo "Generating shared-stream-objstm.pdf ..."
    # 2-page PDF where page 0 shares with page 1 BOTH an ObjStm-eligible font
    # dict (obj 5) AND an ObjStm-ineligible image XObject stream (obj 6). The
    # eligible dict packs into a first-half container; the ineligible stream
    # stays a plain first-half object numbered BEFORE the container. Exercises
    # flpdf-ihb.2: folded shared-hint order must match physical object number.
    python3 - "$FIX/shared-stream-objstm.pdf" <<'PY'
import sys
def obj(n, body): return b"%d 0 obj\n" % n + body + b"\nendobj\n"
img = b"\xff"
c0 = b"BT /F1 12 Tf 100 700 Td (Page0) Tj ET\nq 1 0 0 1 0 0 cm /Im0 Do Q\n"
c1 = b"BT /F1 12 Tf 100 700 Td (Page1) Tj ET\nq 1 0 0 1 0 0 cm /Im0 Do Q\n"
res = b"<< /Font << /F1 5 0 R >> /XObject << /Im0 6 0 R >> >>"
o1 = obj(1, b"<< /Type /Catalog /Pages 2 0 R >>")
o2 = obj(2, b"<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>")
o3 = obj(3, b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources " + res + b" /Contents 7 0 R >>")
o4 = obj(4, b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources " + res + b" /Contents 8 0 R >>")
o5 = obj(5, b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
o6 = obj(6, b"<< /Type /XObject /Subtype /Image /Width 1 /Height 1 /ColorSpace /DeviceGray /BitsPerComponent 8 /Length %d >>\nstream\n" % len(img) + img + b"\nendstream")
o7 = obj(7, b"<< /Length %d >>\nstream\n" % len(c0) + c0 + b"\nendstream")
o8 = obj(8, b"<< /Length %d >>\nstream\n" % len(c1) + c1 + b"\nendstream")
body = b"%PDF-1.5\n%\xe2\xe3\xcf\xd3\n"; offs=[]
for o in (o1,o2,o3,o4,o5,o6,o7,o8): offs.append(len(body)); body+=o
xref=len(body); n=len(offs)+1
body += b"xref\n0 %d\n0000000000 65535 f \n" % n
for off in offs: body += b"%010d 00000 n \n" % off
body += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (n, xref)
open(sys.argv[1],"wb").write(body)
PY
else
    echo "Skipping shared-stream-objstm.pdf (already exists)"
fi

if [[ ! -f "$FIX/one-page-enc-u.pdf" ]]; then
    echo "Generating one-page-enc-u.pdf ..."
    # AES-256 (R6) encrypted source for the overlay --password path. AES key
    # material is random => this fixture is NON-deterministic and is COMMITTED;
    # if regenerated, re-bless overlay/three-page-overlay-encrypted-source.pdf.
    qpdf --encrypt u o 256 -- --warning-exit-0 \
        "$FIX/one-page.pdf" "$FIX/one-page-enc-u.pdf"
else
    echo "Skipping one-page-enc-u.pdf (already exists)"
fi

if [[ ! -f "$FIX/one-page-r90.pdf" ]]; then
    echo "Generating one-page-r90.pdf ..."
    # +90-rotated single page; the Form /Matrix encodes the rotation so the
    # placement uses the matrix-transformed (visual) bbox. Deterministic.
    qpdf "$FIX/one-page.pdf" --rotate=+90:1 -- "$FIX/one-page-r90.pdf"
else
    echo "Skipping one-page-r90.pdf (already exists)"
fi

# Overlay byte-parity widening fixtures (flpdf-9hc.16.10). qpdf's CLI cannot add
# /UserUnit and there is no plain multi-stream-no-/Rotate corpus pinned to PDF
# 1.3, so both are hand-built (correct xref offsets) then normalised through
# `qpdf --force-version=1.3 --static-id` for a clean, deterministic, dest-version
# (three-page is 1.3) fixture. Pinning to 1.3 keeps the orthogonal source
# version-floor limitation out of the overlay byte-gate.
if [[ ! -f "$FIX/userunit-one-page.pdf" ]]; then
    echo "Generating userunit-one-page.pdf ..."
    # Single page with /UserUnit 2 and no /Rotate -> getFormXObjectForPage folds
    # the scale into the Form /Matrix ([2 0 0 2 0 0]).
    python3 - "$FIX/userunit-one-page.pdf" <<'PY'
import subprocess, sys, tempfile, os
objs = [
    b"<< /Type /Catalog /Pages 2 0 R >>",
    b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /UserUnit 2 "
    b"/Resources << /ProcSet [/PDF] >> /Contents 4 0 R >>",
]
content = b"0.5 g 100 100 200 200 re f"
objs.append(b"<< /Length %d >>\nstream\n%s\nendstream" % (len(content), content))
out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
offs = []
for i, body in enumerate(objs, 1):
    offs.append(len(out)); out += b"%d 0 obj\n%s\nendobj\n" % (i, body)
xs = len(out); n = len(objs) + 1
out += b"xref\n0 %d\n0000000000 65535 f \n" % n
for o in offs: out += b"%010d 00000 n \n" % o
out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (n, xs)
with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as t:
    t.write(out); rough = t.name
subprocess.run(["qpdf", "--static-id", "--force-version=1.3", "--warning-exit-0",
                rough, sys.argv[1]], check=True)
os.unlink(rough)
PY
else
    echo "Skipping userunit-one-page.pdf (already exists)"
fi

if [[ ! -f "$FIX/multi-stream-one-page.pdf" ]]; then
    echo "Generating multi-stream-one-page.pdf ..."
    # Two-element /Contents array, no /Rotate; the first stream does not end in a
    # newline, so getFormXObjectForPage's pipeContentStreams inserts a single '\n'
    # between the two streams.
    python3 - "$FIX/multi-stream-one-page.pdf" <<'PY'
import subprocess, sys, tempfile, os
c1 = b"q 1 0 0 1 0 0 cm"
c2 = b"0.5 g 100 100 200 200 re f"
objs = [
    b"<< /Type /Catalog /Pages 2 0 R >>",
    b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
    b"/Resources << /ProcSet [/PDF] >> /Contents [4 0 R 5 0 R] >>",
    b"<< /Length %d >>\nstream\n%s\nendstream" % (len(c1), c1),
    b"<< /Length %d >>\nstream\n%s\nendstream" % (len(c2), c2),
]
out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
offs = []
for i, body in enumerate(objs, 1):
    offs.append(len(out)); out += b"%d 0 obj\n%s\nendobj\n" % (i, body)
xs = len(out); n = len(objs) + 1
out += b"xref\n0 %d\n0000000000 65535 f \n" % n
for o in offs: out += b"%010d 00000 n \n" % o
out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (n, xs)
with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as t:
    t.write(out); rough = t.name
subprocess.run(["qpdf", "--static-id", "--force-version=1.3", "--warning-exit-0",
                rough, sys.argv[1]], check=True)
os.unlink(rough)
PY
else
    echo "Skipping multi-stream-one-page.pdf (already exists)"
fi

# No-stream multipage fixtures for NON-linearized --object-streams=generate
# byte-parity (flpdf-g6hb.1). Every reachable object is an ObjStm-eligible dict
# (no content streams), so the output body is just the ObjStm container(s) plus
# the xref stream — isolating the generate-mode numbering (container-first,
# members ascending-source, even split) from plain-object emission.
#  - 5-page natural: 7 eligible => 1 container (n<=100 single-stream shape).
#  - 130-page reverse: 132 eligible => 2 containers of 66 (ceil(n/100) even
#    split); /Kids listed in descending object number so the getCompressibleObjGens
#    DFS grouping differs from numeric order.
if [[ ! -f "$FIX/objstm-gen-nostream-5.pdf" ]]; then
    echo "Generating objstm-gen-nostream-5.pdf ..."
    python3 "$ROOT/docs/plans/tools/gen_multipage.py" 5 natural \
        > "$FIX/objstm-gen-nostream-5.pdf"
else
    echo "Skipping objstm-gen-nostream-5.pdf (already exists)"
fi

if [[ ! -f "$FIX/objstm-gen-nostream-130rev.pdf" ]]; then
    echo "Generating objstm-gen-nostream-130rev.pdf ..."
    python3 "$ROOT/docs/plans/tools/gen_multipage.py" 130 reverse \
        > "$FIX/objstm-gen-nostream-130rev.pdf"
else
    echo "Skipping objstm-gen-nostream-130rev.pdf (already exists)"
fi

# Linearized generate-mode >cap fixtures (flpdf-g6hb.2). Each forces a distinct
# qpdf even-split + part-routing scenario:
#  - sharedfonts-100: 104 first-page-shared dicts => 2 containers (50+51), both part6.
#  - cap-boundary-199: 199 fonts + /Pages = 200 first-page-shared members (exact
#                     multiple of the 100 cap) => even-split 3 containers
#                     (66+68+66), all part6. The ihb.3 stranded-container
#                     boundary: greedy chunks(cap) would mis-split as 100+100.
#  - mixed-60-70:     first-page-shared + page-1-only => part6 + part7 containers.
#  - threepage-2-120: fonts shared by pages 1&2 (not page 0) => part6 + part8.
#  - disc-2-250-2:    pure part7 container + a part8 uncompressed Form XObject
#                     (the renumber finding-4 discriminator).
#  - openaction-80-80: catalog /OpenAction -> 80 od-only font dicts reachable
#                     only from the root /OpenAction key => qpdf in_open_document
#                     (lc_open_document, part4, first half), plus 80 first-page
#                     shared fonts. Forces the obj_user open_document category.
#  - outlines-80-80:  catalog /Outlines -> outline dict + 80 items reachable only
#                     from the root /Outlines key => qpdf in_outlines (lc_outlines,
#                     part9 second half via pushOutlinesToPart, with the Outlines
#                     hint table + hint dict /O), plus 80 first-page shared fonts.
#  - outline-od-shared-stream: a /JS action stream reachable from BOTH /OpenAction
#                     and an outline item's /A. qpdf orders in_outlines above
#                     in_open_document (lc_outlines wins), and the stream is
#                     ineligible for ObjStm, so qpdf emits it plain in part9 AFTER
#                     the outline container. Discriminates step-6b OD/outline
#                     precedence and the second-half post-container plain ordering.
#  - useoutline-od-shared-stream (flpdf-q9o3): the /PageMode /UseOutlines sibling of
#                     outline-od-shared-stream. The outline objects (and the
#                     ineligible OD+outline /JS stream) route to qpdf part6 (first
#                     half, BEFORE /E) instead of part9. qpdf numbers the ineligible
#                     stream AFTER its part6 ObjStm container, so it is a first-half
#                     post-container plain object — the mirror of the second-half
#                     post-plain pass. Discriminates place_objstm_members_per_half's
#                     first-half post-container plain ordering.
#  - outlines-otherpage-2-60-20 (flpdf-7aek): one ObjStm container co-locates
#                     /Outlines items (in_outlines => part9, no /UseOutlines) with
#                     page-1&2-shared fonts (part8). Outline priority routes the
#                     container to part9; its part8 fonts must NOT appear as part8
#                     Shared Object Hint Table entries. Sized single-container
#                     (eligible 85 < 100) to isolate the SOHT bug from the
#                     even-split page-dict-erasure boundary divergence (flpdf-g1eu).
#  - outlines-otherpage-0-60-20 (flpdf-7aek, Codex P2): same with P0=0 so page 0
#                     has NO ObjStm-eligible private member => the part9 container
#                     has no first-page member. part8_container_nums would re-add it
#                     (enumeration tail) and over-count first_page_entries; both
#                     canonical_shared_hints and from_plan must exclude rest containers.
#  - outlines-otherpage-2-120-20 (flpdf-g1eu): the 2-container variant (eligible
#                     149 > 100 cap => even-split into a part9 mixed container
#                     (outline items + page-0 fonts + 47 shared fonts) and a part8
#                     pure-shared-font container. The even split yields the part9
#                     container FIRST (DFS-early outline items), but qpdf's strict
#                     part order (part8 before part9) emits the shared container
#                     first. Pins that second-half ObjStm containers are emitted in
#                     part rank order, not even-split order.
#  - outlines-otherpage-0-120-20 (flpdf-g1eu, flpdf-7aek forward flag): the
#                     2-container variant with P0=0, so the part9 mixed container
#                     has NO first-page member (page 0 has no ObjStm-eligible
#                     fonts). Confirms the part-rank emission order AND that the
#                     no-first-page-member part9 container does NOT leak into the
#                     Shared Object Hint Table enumeration tail (the flpdf-7aek
#                     guards + part-rank ordering already keep it byte-identical;
#                     no extra part9 enumeration-tail guard is needed).
declare -A G6HB2_FIX=(
    [objstm-lin-sharedfonts-100]="gen_shared_fonts.py 100"
    [objstm-lin-cap-boundary-199]="gen_shared_fonts.py 199"
    [objstm-lin-mixed-60-70]="gen_mixed_shared.py 60 70"
    [objstm-lin-threepage-2-120]="gen_three_page_shared.py 2 120"
    [objstm-lin-disc-2-250-2]="gen_part7_part8_discriminator.py 2 250 2"
    [objstm-lin-openaction-80-80]="gen_open_action_gap.py 80 80"
    [objstm-lin-openaction-multi-od]="gen_openaction_multi_od.py"
    [objstm-lin-outlines-80-80]="gen_outlines_gap.py 80 80"
    [objstm-lin-outlines-80-200]="gen_outlines_gap.py 80 200"
    [objstm-lin-useoutlines-80-80]="gen_outlines_gap.py 80 80 --use-outlines"
    [objstm-lin-outlines-shared-page-80-80]="gen_outlines_shared_page.py 80 80"
    [objstm-lin-outlines-coloc-200-20]="gen_outlines_gap.py 200 20"
    [objstm-lin-outlines-otherpage-2-60-20]="gen_outlines_otherpage_shared.py 2 60 20"
    [objstm-lin-outlines-otherpage-0-60-20]="gen_outlines_otherpage_shared.py 0 60 20"
    [objstm-lin-outlines-otherpage-2-120-20]="gen_outlines_otherpage_shared.py 2 120 20"
    [objstm-lin-outlines-otherpage-0-120-20]="gen_outlines_otherpage_shared.py 0 120 20"
    [objstm-lin-outline-od-shared-stream]="gen_outline_open_action_shared_stream.py"
    [objstm-lin-useoutline-od-shared-stream]="gen_outline_open_action_shared_stream.py --use-outlines"
    [objstm-lin-acroform-widget-page0-5-10]="gen_acroform_widget_page0.py 5 10"
    [objstm-lin-acroform-widget-ap-stream-page0]="gen_acroform_widget_ap_stream_page0.py"
    [objstm-lin-acroform-widget-page1-only]="gen_acroform_widget_page1_only.py"
    [objstm-lin-acroform-widget-page1-page2]="gen_acroform_widget_page1_page2.py"
    [objstm-lin-thumbnail-private-shared]="gen_thumbnail.py"
    [objstm-lin-od-indirect-length]="gen_od_indirect_length.py"
    [objstm-lin-od-indirect-length-flate]="gen_od_indirect_length.py --flate"
    [objstm-lin-page-contents-indirect-length]="gen_page_contents_indirect_length.py"
    [objstm-lin-page-contents-indirect-length-flate]="gen_page_contents_indirect_length.py --flate"
)
for stem in "${!G6HB2_FIX[@]}"; do
    if [[ ! -f "$FIX/$stem.pdf" ]]; then
        echo "Generating $stem.pdf ..."
        # shellcheck disable=SC2086
        python3 "$ROOT/docs/plans/tools/"${G6HB2_FIX[$stem]} > "$FIX/$stem.pdf"
    else
        echo "Skipping $stem.pdf (already exists)"
    fi
done

# ObjStm-bearing variant of the cap-boundary-199 fixture (flpdf-ihb.4). The raw
# gen_shared_fonts.py 199 output has no source ObjStms, so --object-streams=preserve
# on it yields an empty plan. Re-encoding through --object-streams=generate produces
# 3 source ObjStm containers (68/67/68 members) so the preserve path has real source
# grouping to preserve at >cap. qpdf 11.9.0 does not support reading a PDF from stdin
# ("reading from stdin is not supported"), so the generator output is staged to a
# temp file rather than piped. --deterministic-id keeps the fixture byte-reproducible.
if [[ ! -f "$FIX/objstm-lin-cap-boundary-199-bearing.pdf" ]]; then
    echo "Generating objstm-lin-cap-boundary-199-bearing.pdf ..."
    bearing_src="$(mktemp)"
    python3 "$ROOT/docs/plans/tools/gen_shared_fonts.py" 199 > "$bearing_src"
    qpdf --object-streams=generate --deterministic-id --warning-exit-0 \
        "$bearing_src" "$FIX/objstm-lin-cap-boundary-199-bearing.pdf"
    rm -f "$bearing_src"
else
    echo "Skipping objstm-lin-cap-boundary-199-bearing.pdf (already exists)"
fi

echo ""

# ---------------------------------------------------------------------------
# Phase 2: Generate reference outputs (always regenerate)
# ---------------------------------------------------------------------------

mkdir -p \
    "$REF/one-page" \
    "$REF/two-page" \
    "$REF/three-page" \
    "$REF/linearized-one-page" \
    "$REF/encrypted-r4-three-page" \
    "$REF/attachment-two-page" \
    "$REF/lone-flate-l9" \
    "$REF/objstm-gen-nostream-5" \
    "$REF/objstm-gen-nostream-130rev"

echo "=== Generating reference outputs ==="

# --- one-page: plain, static-id, linearize ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/one-page.pdf" "$REF/one-page/plain.pdf"
echo "one-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/one-page.pdf" "$REF/one-page/static-id.pdf"
echo "one-page/static-id.pdf"

qpdf --linearize --deterministic-id --warning-exit-0 \
    "$FIX/one-page.pdf" "$REF/one-page/linearize.pdf"
echo "one-page/linearize.pdf"

# --- two-page: plain, static-id, linearize ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/two-page.pdf" "$REF/two-page/plain.pdf"
echo "two-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/two-page.pdf" "$REF/two-page/static-id.pdf"
echo "two-page/static-id.pdf"

qpdf --linearize --deterministic-id --warning-exit-0 \
    "$FIX/two-page.pdf" "$REF/two-page/linearize.pdf"
echo "two-page/linearize.pdf"

# Linearized + object streams (cross-reference *stream* path; header floored to
# 1.5). The byte-identity gate for this output is feature-gated on qpdf-zlib-compat.
qpdf --linearize --object-streams=generate --deterministic-id --warning-exit-0 \
    "$FIX/two-page.pdf" "$REF/two-page/linearize-objstm.pdf"
echo "two-page/linearize-objstm.pdf"

# --- three-page: plain, static-id, linearize ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/plain.pdf"
echo "three-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/static-id.pdf"
echo "three-page/static-id.pdf"

qpdf --linearize --deterministic-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/linearize.pdf"
echo "three-page/linearize.pdf"

# Linearized + object streams (cross-reference *stream* path; header floored to
# 1.5). The byte-identity gate for this output is feature-gated on qpdf-zlib-compat.
qpdf --linearize --object-streams=generate --deterministic-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/linearize-objstm.pdf"
echo "three-page/linearize-objstm.pdf"

# Linearized --object-streams=generate with a forced sub-1.5 header: object and
# cross-reference streams are suppressed (PDF 1.5 features under a forced 1.4
# cap), so the output is a CLASSIC linearized PDF at header 1.4 — identical to
# the disable path. Exercises the suppression gate on the linearize writer
# (flpdf-ipc6); feature-gated on qpdf-zlib-compat.
qpdf --linearize --object-streams=generate --force-version=1.4 --deterministic-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/linearize-objstm-force14.pdf"
echo "three-page/linearize-objstm-force14.pdf"

# --- three-page-objstm: linearize an ObjStm-bearing input (flpdf-zbf9) ---
# qpdf drops the source structural containers; this golden is qpdf's OWN
# linearization of the ObjStm-bearing input (NOT identical to three-page's,
# since qpdf preserves each stream's input dict key order).
mkdir -p "$REF/three-page-objstm"
qpdf --linearize --object-streams=generate --deterministic-id --warning-exit-0 \
    "$FIX/three-page-objstm.pdf" "$REF/three-page-objstm/linearize-objstm.pdf"
echo "three-page-objstm/linearize-objstm.pdf"

# Forced sub-1.5 header on an ObjStm/xref-stream SOURCE: qpdf keeps the 1.4 header
# and DOWNGRADES the inherited xref stream + ObjStm to a classic table (it does
# not clamp the version up). preserve/disable/generate are byte-identical here, so
# the preserve golden anchors the whole class. Feature-gated on qpdf-zlib-compat
# (flpdf-w35w). Non-linearized (full-rewrite) and linearized counterparts:
qpdf --object-streams=preserve --force-version=1.4 --static-id --warning-exit-0 \
    "$FIX/three-page-objstm.pdf" "$REF/three-page-objstm/downgrade-force14.pdf"
echo "three-page-objstm/downgrade-force14.pdf"
qpdf --linearize --object-streams=preserve --force-version=1.4 --deterministic-id --warning-exit-0 \
    "$FIX/three-page-objstm.pdf" "$REF/three-page-objstm/linearize-downgrade-force14.pdf"
echo "three-page-objstm/linearize-downgrade-force14.pdf"

# NON-linearized --object-streams=generate (cross-reference *stream* form, header
# floored to 1.5). --static-id keeps /ID byte-stable: /ID[0] is the preserved
# source identifier (or the pi constant when the source has none) and /ID[1] is
# the pi constant — both reproducible, so the parity gate is strict (no /ID
# masking). Gated on qpdf-zlib-compat (flpdf-g6hb.1). three-page interleaves
# plain content streams with the ObjStm container; the no-stream fixtures isolate
# the numbering.
qpdf --object-streams=generate --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/generate.pdf"
echo "three-page/generate.pdf"

qpdf --object-streams=generate --static-id --warning-exit-0 \
    "$FIX/objstm-gen-nostream-5.pdf" "$REF/objstm-gen-nostream-5/generate.pdf"
echo "objstm-gen-nostream-5/generate.pdf"

qpdf --object-streams=generate --static-id --warning-exit-0 \
    "$FIX/objstm-gen-nostream-130rev.pdf" "$REF/objstm-gen-nostream-130rev/generate.pdf"
echo "objstm-gen-nostream-130rev/generate.pdf"

# --object-streams=generate with a forced sub-1.5 header: object streams and
# cross-reference streams are PDF 1.5 features, so qpdf suppresses both under a
# forced version it must not exceed and falls back to a classic xref table while
# keeping the 1.4 header (i.e. generate+force1.4 == disable+force1.4). The parity
# gate for this suppression is feature-gated on qpdf-zlib-compat (flpdf-ipc6).
qpdf --object-streams=generate --force-version=1.4 --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/generate-force14.pdf"
echo "three-page/generate-force14.pdf"

# --- linearized-one-page: plain only (re-linearize would be redundant) ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/linearized-one-page.pdf" "$REF/linearized-one-page/plain.pdf"
echo "linearized-one-page/plain.pdf"

# --- encrypted-r4-three-page: plain only
# Note: qpdf decrypts using the empty user password by default.
# --deterministic-id is incompatible with encrypted input.
# --decrypt ensures deterministic output; --static-id stabilises the /ID array.
qpdf --decrypt --static-id --warning-exit-0 \
    "$FIX/encrypted-r4-three-page.pdf" "$REF/encrypted-r4-three-page/plain.pdf"
echo "encrypted-r4-three-page/plain.pdf"

# --- attachment-two-page: plain, static-id ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/attachment-two-page.pdf" "$REF/attachment-two-page/plain.pdf"
echo "attachment-two-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/attachment-two-page.pdf" "$REF/attachment-two-page/static-id.pdf"
echo "attachment-two-page/static-id.pdf"

# --- lone-flate-l9: static-id (plain) + linearize. Both PRESERVE the level-9
#     lone /FlateDecode streams verbatim (qpdf default; no --recompress-flate). ---
qpdf --static-id --warning-exit-0 \
    "$FIX/lone-flate-l9.pdf" "$REF/lone-flate-l9/static-id.pdf"
echo "lone-flate-l9/static-id.pdf"

qpdf --linearize --deterministic-id --warning-exit-0 \
    "$FIX/lone-flate-l9.pdf" "$REF/lone-flate-l9/linearize.pdf"
echo "lone-flate-l9/linearize.pdf"

# --- shared-stream-objstm: linearized + object streams. Page 0 shares an
#     ObjStm-eligible font dict AND an ObjStm-ineligible image stream with
#     page 1; the folded shared-object hint table must list the plain stream
#     before the container in physical object-number order (flpdf-ihb.2). ---
mkdir -p "$REF/shared-stream-objstm"
qpdf --linearize --object-streams=generate --deterministic-id --warning-exit-0 \
    "$FIX/shared-stream-objstm.pdf" "$REF/shared-stream-objstm/linearize-objstm.pdf"
qpdf --check "$REF/shared-stream-objstm/linearize-objstm.pdf" >/dev/null
echo "shared-stream-objstm/linearize-objstm.pdf"

# Linearized generate-mode >cap goldens (flpdf-g6hb.2). See the fixture block
# above for each scenario. Compared structurally (and strictly where flpdf
# reaches byte-identity) by cmp_linearize_objstm_tests under qpdf-zlib-compat.
for stem in objstm-lin-sharedfonts-100 objstm-lin-cap-boundary-199 \
            objstm-lin-mixed-60-70 \
            objstm-lin-threepage-2-120 objstm-lin-disc-2-250-2 \
            objstm-lin-openaction-80-80 objstm-lin-openaction-multi-od \
            objstm-lin-outlines-80-80 \
            objstm-lin-outlines-80-200 objstm-lin-useoutlines-80-80 \
            objstm-lin-outlines-shared-page-80-80 objstm-lin-outlines-coloc-200-20 \
            objstm-lin-outlines-otherpage-2-60-20 \
            objstm-lin-outlines-otherpage-0-60-20 \
            objstm-lin-outlines-otherpage-2-120-20 \
            objstm-lin-outlines-otherpage-0-120-20 \
            objstm-lin-outline-od-shared-stream \
            objstm-lin-useoutline-od-shared-stream \
            objstm-lin-acroform-widget-page0-5-10 \
            objstm-lin-acroform-widget-ap-stream-page0 \
            objstm-lin-acroform-widget-page1-only \
            objstm-lin-acroform-widget-page1-page2 \
            objstm-lin-thumbnail-private-shared \
            objstm-lin-od-indirect-length objstm-lin-od-indirect-length-flate \
            objstm-lin-page-contents-indirect-length \
            objstm-lin-page-contents-indirect-length-flate; do
    mkdir -p "$REF/$stem"
    qpdf --linearize --object-streams=generate --deterministic-id --warning-exit-0 \
        "$FIX/$stem.pdf" "$REF/$stem/linearize-objstm.pdf"
    qpdf --check "$REF/$stem/linearize-objstm.pdf" >/dev/null
    echo "$stem/linearize-objstm.pdf"
done

# Plain full-rewrite + non-linearized generate goldens for the orphaned-/Length-
# holder drop (flpdf-sqkq). The OD fixtures' indirect /Length holder (obj 7) is
# reachable only via the JS stream's /Length; once /Length is normalized to a
# direct integer it orphans and qpdf garbage-collects it. Pinned byte-identical
# by cmp_diff_zero_tests (static-id) and cmp_generate_objstm_tests (generate)
# under qpdf-zlib-compat.
for stem in objstm-lin-od-indirect-length objstm-lin-od-indirect-length-flate; do
    qpdf --static-id --warning-exit-0 \
        "$FIX/$stem.pdf" "$REF/$stem/static-id.pdf"
    echo "$stem/static-id.pdf"
    qpdf --object-streams=generate --static-id --warning-exit-0 \
        "$FIX/$stem.pdf" "$REF/$stem/generate.pdf"
    echo "$stem/generate.pdf"
done

# Plain full-rewrite golden for the KEPT indirect-/Length-holder case (flpdf-q1j2),
# the dual of the orphan OD fixtures above. The image XObject (obj 5) is a
# /DCTDecode passthrough (flpdf cannot decode it) carrying an INDIRECT /Length
# (6 0 R) whose holder (obj 6) is ALSO referenced by the catalog (/KeepHolder),
# so it stays live. qpdf direct-izes /Length to the raw byte count while KEEPING
# the holder (it has another live reference). Pinned byte-identical by
# cmp_diff_zero_tests under qpdf-zlib-compat. NOTE: only a flat (static-id) golden
# is committed; the linearized output for this object graph diverges from qpdf on
# an unrelated, pre-existing object-numbering axis (flpdf-lubb-class), so no
# linearize golden is blessed here.
if [[ ! -f "$FIX/kept-indirect-length.pdf" ]]; then
    echo "Generating kept-indirect-length.pdf ..."
    python3 "$ROOT/docs/plans/tools/gen_kept_indirect_length.py" > "$FIX/kept-indirect-length.pdf"
else
    echo "Skipping kept-indirect-length.pdf (already exists)"
fi
mkdir -p "$REF/kept-indirect-length"
qpdf --static-id --warning-exit-0 \
    "$FIX/kept-indirect-length.pdf" "$REF/kept-indirect-length/static-id.pdf"
echo "kept-indirect-length/static-id.pdf"

# Linearized >cap preserve golden for the ObjStm-bearing fixture (flpdf-ihb.4).
# Distinct filename (linearize-objstm-preserve.pdf) so it never collides with the
# generate-mode linearize-objstm.pdf goldens. preserve keeps qpdf's source ObjStm
# grouping (68/67/68) minus the erased /Catalog + /Page dicts => 3 containers
# 66/66/68 in the linearized output.
mkdir -p "$REF/objstm-lin-cap-boundary-199-bearing"
qpdf --linearize --object-streams=preserve --deterministic-id --warning-exit-0 \
    "$FIX/objstm-lin-cap-boundary-199-bearing.pdf" \
    "$REF/objstm-lin-cap-boundary-199-bearing/linearize-objstm-preserve.pdf"
echo "objstm-lin-cap-boundary-199-bearing/linearize-objstm-preserve.pdf"

# Classic (non-ObjStm) linearize goldens for outline section routing (flpdf-vvjr.2).
# outlines-80-80: outlines route to part9 (second-half, !UseOutlines).
# useoutlines-80-80: outlines route to part6 (first-page section, UseOutlines).
# Pinned to linearize-classic.pdf to coexist with the ObjStm golden in the same dir.
for stem in objstm-lin-outlines-80-80 objstm-lin-useoutlines-80-80; do
    mkdir -p "$REF/$stem"
    qpdf --linearize --deterministic-id --warning-exit-0 \
        "$FIX/$stem.pdf" "$REF/$stem/linearize-classic.pdf"
    qpdf --check "$REF/$stem/linearize-classic.pdf" >/dev/null
    echo "$stem/linearize-classic.pdf"
done

echo ""
echo "=== All references generated ==="

# ---------------------------------------------------------------------------
# Phase 2b: Overlay / underlay reference outputs (epic flpdf-9hc.16)
# ---------------------------------------------------------------------------

mkdir -p "$REF/overlay"

# Simplest overlay: 1-page source onto page 1 of a 3-page dest (identity cm,
# same MediaBox). --static-id pins the trailer /ID. Source exhausts after page 1
# (no --repeat) so pages 2-3 are untouched. This is the .16.3 byte-identity gate.
qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/one-page.pdf" -- \
    "$REF/overlay/three-page-overlay-one-page.pdf"
echo "overlay/three-page-overlay-one-page.pdf"

# Page-range mapping variants (epic flpdf-9hc.16.4):
#  - default: 2-page source onto 3-page dest -> p1<-s1, p2<-s2, p3 untouched.
#  - --repeat=1: 1-page source repeated onto all 3 dest pages.
#  - --to=2-3: 2-page source paired with dest pages 2,3 (p1 untouched).
qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/two-page.pdf" -- \
    "$REF/overlay/three-page-overlay-two-page.pdf"
echo "overlay/three-page-overlay-two-page.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/one-page.pdf" --repeat=1 -- \
    "$REF/overlay/three-page-overlay-one-page-repeat1.pdf"
echo "overlay/three-page-overlay-one-page-repeat1.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/two-page.pdf" --to=2-3 -- \
    "$REF/overlay/three-page-overlay-two-page-to2-3.pdf"
echo "overlay/three-page-overlay-two-page-to2-3.pdf"

# Multi-spec composition (epic flpdf-9hc.16.5):
#  - two --overlay flags compose left-to-right (both onto the same pages).
#  - --overlay + --underlay: underlay below, overlay above, page in the middle.
qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/one-page.pdf" -- \
    --overlay "$FIX/two-page.pdf" -- \
    "$REF/overlay/three-page-two-overlays.pdf"
echo "overlay/three-page-two-overlays.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/one-page.pdf" -- \
    --underlay "$FIX/two-page.pdf" -- \
    "$REF/overlay/three-page-overlay-and-underlay.pdf"
echo "overlay/three-page-overlay-and-underlay.pdf"

# Matrix coverage (epic flpdf-9hc.16.7): --from range, pure --underlay, rotated
# source (matrix-transformed placement), and --to + --repeat together.
qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/two-page.pdf" --from=2 -- \
    "$REF/overlay/three-page-overlay-two-page-from2.pdf"
echo "overlay/three-page-overlay-two-page-from2.pdf"

# Explicit empty --from= (distinct from an absent --from): qpdf treats it as an
# empty source set, so --repeat cycles from the first dest page. Here from={},
# repeat={2} -> every dest page receives source page 2 (NOT s1,s2 then exhausted).
qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/two-page.pdf" --from= --repeat=2 -- \
    "$REF/overlay/three-page-overlay-two-page-from-empty-repeat2.pdf"
echo "overlay/three-page-overlay-two-page-from-empty-repeat2.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --underlay "$FIX/two-page.pdf" -- \
    "$REF/overlay/three-page-underlay-two-page.pdf"
echo "overlay/three-page-underlay-two-page.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/one-page-r90.pdf" -- \
    "$REF/overlay/three-page-overlay-rotated.pdf"
echo "overlay/three-page-overlay-rotated.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/one-page.pdf" --to=1-3 --repeat=1 -- \
    "$REF/overlay/three-page-overlay-to-repeat.pdf"
echo "overlay/three-page-overlay-to-repeat.pdf"

# Byte-parity widening (flpdf-9hc.16.10):
#  - multi-stream source: no /Rotate -> imported Form XObject OMITS /Matrix, and
#    its two content streams coalesce with a single '\n' (gaps 1 + 2).
#  - rotated dest: the dest inverse transform folds into BOTH the /Fx0 and source
#    placement cm (gap 3).
#  - /UserUnit source: the imported Form /Matrix folds the unit scale in (gap 4).
qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/multi-stream-one-page.pdf" -- \
    "$REF/overlay/three-page-overlay-multi-stream.pdf"
echo "overlay/three-page-overlay-multi-stream.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/one-page-r90.pdf" --overlay "$FIX/one-page.pdf" -- \
    "$REF/overlay/r90-dest-overlay-one-page.pdf"
echo "overlay/r90-dest-overlay-one-page.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" --overlay "$FIX/userunit-one-page.pdf" -- \
    "$REF/overlay/three-page-overlay-userunit.pdf"
echo "overlay/three-page-overlay-userunit.pdf"


echo ""

# ---------------------------------------------------------------------------
# Phase 3: Size check (fail if any reference exceeds 100 KB)
# ---------------------------------------------------------------------------

echo ""
echo "=== Size check (limit: 100 KB per file) ==="
LIMIT=$((100 * 1024))
FAILED=0
# Portable file size: GNU stat uses -c%s, BSD/macOS stat uses -f%z.
file_size() {
    if size=$(stat -c%s "$1" 2>/dev/null); then
        printf '%s' "$size"
    else
        stat -f%z "$1"
    fi
}
while IFS= read -r -d '' f; do
    size=$(file_size "$f")
    rel="${f#"$ROOT"/}"
    if [[ "$size" -gt "$LIMIT" ]]; then
        echo "OVER LIMIT: $rel ($size bytes)"
        FAILED=1
    else
        echo "OK: $rel ($size bytes)"
    fi
done < <(find "$REF" -name "*.pdf" -print0 | sort -z)

if [[ "$FAILED" -eq 1 ]]; then
    echo ""
    echo "ERROR: One or more reference files exceed 100 KB limit." >&2
    exit 1
fi

echo ""
echo "Done."
