#!/usr/bin/env bash
set -euo pipefail

# Regenerate all golden reference outputs under tests/golden/references/.
# Also regenerates derived fixtures under tests/fixtures/compat/ if they don't exist.
#
# Requirements: qpdf 11.9.0 (exact version) installed on PATH — golden bytes
# are tied to a specific upstream zlib/encoder flavour so a different qpdf
# would silently drift the references.
# Usage: bash tests/golden/regenerate.sh

ROOT="$(git rev-parse --show-toplevel)"
FIX="$ROOT/tests/fixtures/compat"
REF="$ROOT/tests/golden/references"

REQUIRED_QPDF_VERSION="11.9.0"

echo "=== qpdf version ==="
ACTUAL_QPDF_VERSION="$(qpdf --version | head -1 | awk '{print $3}')"
echo "qpdf version $ACTUAL_QPDF_VERSION (required: $REQUIRED_QPDF_VERSION)"
if [[ "$ACTUAL_QPDF_VERSION" != "$REQUIRED_QPDF_VERSION" ]]; then
    echo "ERROR: qpdf $REQUIRED_QPDF_VERSION is required for byte-stable golden" >&2
    echo "       outputs; got $ACTUAL_QPDF_VERSION. Install the required version" >&2
    echo "       or bump tests/golden/README.md and re-bless the matrix." >&2
    exit 1
fi
echo ""

# ---------------------------------------------------------------------------
# Phase 1: Derive new fixtures from existing base fixtures (skip if present)
# ---------------------------------------------------------------------------

if [[ ! -f "$FIX/linearized-one-page.pdf" ]]; then
    echo "Generating linearized-one-page.pdf ..."
    qpdf --linearize --warning-exit-0 "$FIX/one-page.pdf" "$FIX/linearized-one-page.pdf"
else
    echo "Skipping linearized-one-page.pdf (already exists)"
fi

if [[ ! -f "$FIX/encrypted-r4-three-page.pdf" ]]; then
    echo "Generating encrypted-r4-three-page.pdf ..."
    qpdf --encrypt "" "" 128 --use-aes=y -- --warning-exit-0 \
        "$FIX/three-page.pdf" "$FIX/encrypted-r4-three-page.pdf"
else
    echo "Skipping encrypted-r4-three-page.pdf (already exists)"
fi

if [[ ! -f "$FIX/attachment-two-page.pdf" ]]; then
    echo "Generating attachment-two-page.pdf ..."
    # 1) Create a private temp directory (avoids the world-writable /tmp
    #    symlink-attack surface) and use a stable basename inside it.
    # 2) qpdf's --key / --filename force the embedded attachment metadata
    #    names regardless of the source path's directory.
    # 3) --static-id on the main qpdf invocation pins the trailer /ID so
    #    the output is byte-stable across runs (without it qpdf seeds the
    #    /ID from time and file metadata).
    TMPDIR_ATT="$(mktemp -d)"
    TMPFILE="$TMPDIR_ATT/attachment.txt"
    trap 'rm -rf "$TMPDIR_ATT"' EXIT
    printf "This is a small text attachment for PDF fixture testing.\nGenerated by flpdf test corpus setup.\n" \
        > "$TMPFILE"
    qpdf --add-attachment "$TMPFILE" \
        --key=attachment.txt \
        --filename=attachment.txt \
        --creationdate=D:20260101000000Z \
        --moddate=D:20260101000000Z \
        -- --warning-exit-0 --static-id \
        "$FIX/two-page.pdf" "$FIX/attachment-two-page.pdf"
    trap - EXIT
    rm -rf "$TMPDIR_ATT"
else
    echo "Skipping attachment-two-page.pdf (already exists)"
fi

echo ""

# ---------------------------------------------------------------------------
# Phase 2: Generate reference outputs (always regenerate)
# ---------------------------------------------------------------------------

mkdir -p \
    "$REF/one-page" \
    "$REF/two-page" \
    "$REF/three-page" \
    "$REF/linearized-one-page" \
    "$REF/encrypted-r4-three-page" \
    "$REF/attachment-two-page"

echo "=== Generating reference outputs ==="

# --- one-page: plain, static-id, linearize ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/one-page.pdf" "$REF/one-page/plain.pdf"
echo "one-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/one-page.pdf" "$REF/one-page/static-id.pdf"
echo "one-page/static-id.pdf"

qpdf --linearize --deterministic-id --warning-exit-0 \
    "$FIX/one-page.pdf" "$REF/one-page/linearize.pdf"
echo "one-page/linearize.pdf"

# --- two-page: plain, static-id, linearize ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/two-page.pdf" "$REF/two-page/plain.pdf"
echo "two-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/two-page.pdf" "$REF/two-page/static-id.pdf"
echo "two-page/static-id.pdf"

qpdf --linearize --deterministic-id --warning-exit-0 \
    "$FIX/two-page.pdf" "$REF/two-page/linearize.pdf"
echo "two-page/linearize.pdf"

# --- three-page: plain, static-id, linearize ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/plain.pdf"
echo "three-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/static-id.pdf"
echo "three-page/static-id.pdf"

qpdf --linearize --deterministic-id --warning-exit-0 \
    "$FIX/three-page.pdf" "$REF/three-page/linearize.pdf"
echo "three-page/linearize.pdf"

# --- linearized-one-page: plain only (re-linearize would be redundant) ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/linearized-one-page.pdf" "$REF/linearized-one-page/plain.pdf"
echo "linearized-one-page/plain.pdf"

# --- encrypted-r4-three-page: plain only
# Note: qpdf decrypts using the empty user password by default.
# --deterministic-id is incompatible with encrypted input.
# --decrypt ensures deterministic output; --static-id stabilises the /ID array.
qpdf --decrypt --static-id --warning-exit-0 \
    "$FIX/encrypted-r4-three-page.pdf" "$REF/encrypted-r4-three-page/plain.pdf"
echo "encrypted-r4-three-page/plain.pdf"

# --- attachment-two-page: plain, static-id ---
qpdf --deterministic-id --warning-exit-0 \
    "$FIX/attachment-two-page.pdf" "$REF/attachment-two-page/plain.pdf"
echo "attachment-two-page/plain.pdf"

qpdf --static-id --warning-exit-0 \
    "$FIX/attachment-two-page.pdf" "$REF/attachment-two-page/static-id.pdf"
echo "attachment-two-page/static-id.pdf"

echo ""
echo "=== All 13 references generated ==="

# ---------------------------------------------------------------------------
# Phase 3: Size check (fail if any reference exceeds 100 KB)
# ---------------------------------------------------------------------------

echo ""
echo "=== Size check (limit: 100 KB per file) ==="
LIMIT=$((100 * 1024))
FAILED=0
while IFS= read -r -d '' f; do
    size=$(stat -c%s "$f")
    rel="${f#"$ROOT"/}"
    if [[ "$size" -gt "$LIMIT" ]]; then
        echo "OVER LIMIT: $rel ($size bytes)"
        FAILED=1
    else
        echo "OK: $rel ($size bytes)"
    fi
done < <(find "$REF" -name "*.pdf" -print0 | sort -z)

if [[ "$FAILED" -eq 1 ]]; then
    echo ""
    echo "ERROR: One or more reference files exceed 100 KB limit." >&2
    exit 1
fi

echo ""
echo "Done."
